- helix-query.yaml
> We need some additional metadata fields

- blocks/lede/lede.css
- blocks/lede/lede.js
- blocks/pull-quote/pull-quote.css
- blocks/pull-quote/pull-quote.js
- styles/styles.css
Adds styling for pull quotes, and refines the styles for story detail pages.
- https://feat--story-detail--design-website--adobe.hlx3.page/
- you can click-through on any of the stories here to see the detail pages: https://feat--story-detail--design-website--adobe.hlx3.page/stories/
> feat: story detail page styling refinements

- blocks/stories/stories.css
- blocks/stories/stories.js
This refines some of the homepage styling. Namely, it colors the backgrounds for the stories, it adjusts the images and keeps them (visually) equal to the content at medium and large breakpoints.
- https://chore--homepage-refinement--design-website--adobe.hlx3.page/
> refactor: homepage styling refinements for bg colors, images

- scripts/scripts.js
https://relative-links--design-website--adobe.hlx.live/
vs. 
https://main--design-website--adobe.hlx.live/
links across `<header>`, `<main>` and `<footer>` should be relative now.
> chore: make links relative

- blocks/carousel/carousel.css
- blocks/footer/footer.css
- blocks/image-with-caption/image-with-caption.css
- blocks/lede/lede.css
- blocks/pull-quote/pull-quote.css
- blocks/stories/stories.css
- blocks/story-feed/story-feed.css
- styles/styles.css
This resolves a number of font issues, including:
* using the incorrect font-weight for Adobe Clean Black
* using the incorrect font-sizes for various elements (particularly within story detail pages aka. "lede")
- https://fix--initial-feedback--design-website--adobe.hlx3.page/
> fix: resolve site-wide font issues

- blocks/carousel/carousel.css
- blocks/header/header.css
@pfulton let me know if this works for you, I just removed the bg of the header and added padding to the carousel.  
- https://feat--header-color--design-website--adobe.hlx3.page/
> Fix Bg of header

- blocks/columns/columns.css
- blocks/columns/columns.js
- blocks/jobs/jobs.css
- blocks/jobs/jobs.js
- blocks/stats/stats.css
- blocks/stats/stats.js
- scripts/scripts.js
- https://feat--home-jobs--design-website--adobe.hlx3.page/
> feat: adds & styles homepage jobs & stats blocks

- blocks/header/header.css
- blocks/lede/lede.css
- blocks/lede/lede.js
- blocks/people/people.css
- blocks/stories/stories.css
- blocks/story-feed/story-feed.css
- https://chore--profile-images--design-website--adobe.hlx3.page/
> chore: handle profile page images & refine aspect ratios on landing pages

- blocks/stats/stats.css
- blocks/story-feed/story-feed.css
- blocks/story-feed/story-feed.js
Updates the Stories landing page so that the page title and the stats block are now styled. Also refactors the CSS for the stats so that similarly scoped media query styles are grouped together.
- https://chore--stories-landing-cleanup--design-website--adobe.hlx3.page/
> chore: styling for title, stats block on stories landing page

- blocks/lede/lede.css
- blocks/lede/lede.js
Adds author attribution to the story detail pages and profile detail pages.
- https://feat--story-author-attribution--design-website--adobe.hlx3.page/
> feat: author attribution for story detail pages

- blocks/stories/stories.js
- blocks/story-feed/story-feed.js
@davidnuescheler helped index the tags and add titles to the index.  The titles and tags are now populated by the index for #34 , #50, #51, #53
- https://feat--copy-updates--design-website--adobe.hlx3.page/
> add tags and titles to story cards

- blocks/carousel/carousel.css
- blocks/carousel/carousel.js
- blocks/columns/columns.css
- blocks/footer/footer.css
- blocks/header/header.css
- blocks/lede/lede.css
- blocks/people/people.css
- blocks/stats/stats.css
- blocks/stories/stories.css
- blocks/story-feed/story-feed.css
- blocks/team-accordion/team-accordion.css
- styles/styles.css
Adjust layout of header and create content-width variable which was reduced from 95%.
- https://feat--header-updates--design-website--adobe.hlx3.page/
> header updates

- blocks/product-clouds/product-clouds.css
- blocks/product-clouds/product-clouds.js
- blocks/team-accordion/team-accordion.css
- blocks/team-accordion/team-accordion.js
Adds a new block for the "product clouds" section on the team page.
Resolves #52 
- https://chore--team-design-org-block--design-website--adobe.hlx3.page/
> feat: product clouds section of team page

- scripts/scripts.js
- styles/styles.css
Addresses: #71 & #72 
- https://feat--job-disclosures--design-website--adobe.hlx3.page/
> wip: basic styling for disclosure statements

- scripts/scripts.js
https://redirect--design-website--adobe.hlx3.page/toolkit/inclusive-design-card
https://redirect--design-website--adobe.hlx3.page/toolkit/inclusive-design-card?suppress-redirect
> feat: redirect

- blocks/callout/callout.css
- blocks/cards/cards.css
- blocks/cards/cards.js
- blocks/collaborators/collaborators.css
- blocks/collaborators/collaborators.js
- blocks/inclusive-card/inclusive-card.css
- blocks/inclusive-card/inclusive-card.js
- blocks/product-clouds/product-clouds.js
work on inclusive design page.
- https://feat--inclusive-design--design-website--adobe.hlx3.page/toolkit/inclusive-design/
Refs #59
> inclusive design layout

- blocks/opportunities/opportunities.css
- blocks/opportunities/opportunities.js
Addresses:
* Closes #87
* removes "undefined" job departments
* Closes #97 
- https://fix-job-landing-polish--design-website--adobe.hlx3.page/
> fix: jobs landing page polish

- blocks/pull-quote/pull-quote.css
- blocks/pull-quote/pull-quote.js
- styles/styles.css
Closes #95
- https://chore-pull-quotes--design-website--adobe.hlx3.page/
> chore: prefer more accessible text color for pull quotes

- blocks/lede/lede.css
- scripts/scripts.js
Closes #88
- https://chore-profile-polish--design-website--adobe.hlx3.page/
> chore: only show profile layout for profile stories, not all 'our-people' stories

- scripts/scripts.js
- styles/styles.css
Closes #125
- https://feat-jobs-extra-apply-button--design-website--adobe.hlx3.page/
> feat: add additional apply now button to bottom of mobile-sized job post

- blocks/header/header.css
Closes #107
- https://fix-nav-sizing--design-website--adobe.hlx3.page/
> fix: logo, tagline, and nav items running together on medium screens

- styles/styles.css
Closes #122
- https://fix-broken-apply-button--design-website--adobe.hlx3.page/
> fix: prevent line break in apply now button

- blocks/stats/stats.css
Closes #101 
- https://fix-think-differently-formatting--design-website--adobe.hlx3.page/
> fix: think differently formatting

- blocks/stories/stories.css
- blocks/stories/stories.js
Closes #126 
- https://fix-homepage-copy-centering--design-website--adobe.hlx3.page/
> fix: ensure centering for homepage cards

- blocks/carousel/carousel.css
- blocks/opportunities/opportunities.css
- styles/styles.css
This changes the overall layout of the site, so that container elements take up more width
- https://chore-mobile-max-width--design-website--adobe.hlx3.page/
> chore: change overall width of site layout

- blocks/opportunities/opportunities.js
This changes the order of how job listings are posted. Instead of rendering with no specific order, we now rely on the block data from Word, and then manipulate the job postings based upon that data.
Closes #86 
- https://chore-jobs-order--design-website--adobe.hlx3.page/
> feat: render jobs in specific order

- blocks/footer/footer.css
This adjusts the columns in the footer to ensure that the logo stays pinned to the left at medium sizes.
This also cleans up some of the CSS, preferring a simpler syntax for column starts/ends.
Closes #149
- https://fix-footer-width--design-website--adobe.hlx3.page/
> fix: AD logo should remain flush in the footer

- head.html
This adds the Adobe analytics script to the site.
Closes #100
- https://feat-analytics-script--design-website--adobe.hlx3.page/
> feat: add analytics script

- blocks/cards/cards.js
- https://fix-card-links--design-website--adobe.hlx3.page/
> fix: do not show card links on inclusive design page

- blocks/lede/lede.css
Closes #116
- https://fix-adjust-attr-spacing--design-website--adobe.hlx3.page/
> fix: adjust author headshot & article lede padding

- blocks/people/people.js
Closes #165
- https://chore-people-tags--design-website--adobe.hlx3.page/
> chore: update people cards to include dynamic tags

- blocks/lede/lede.css
- blocks/people/people.css
- blocks/pull-quote/pull-quote.css
- blocks/stats/stats.css
- blocks/stories/stories.css
- blocks/stories/stories.js
- blocks/team-accordion/team-accordion.css
- blocks/team-accordion/team-accordion.js
- styles/styles.css
- https://fix-overall-font-spacing--design-website--adobe.hlx3.page/
- Closes #163
- Closes #166 
- Closes #168 
- Closes #169
- Closes #175
> chore: various font and spacing adjustments to story detail & homepage

- blocks/cards/cards.css
- blocks/stories/stories.css
- blocks/story-feed/story-feed.css
- https://fix-small-screens--design-website--adobe.hlx3.page/
> fix: normalize inner padding for cards

- blocks/stories/stories.css
- https://chore-home-centering--design-website--adobe.hlx3.page/
> chore: center homepage card body

- blocks/cards/cards.css
- blocks/cards/cards.js
- blocks/collaborators/collaborators.css
- blocks/lede/lede.css
- blocks/lede/lede.js
- blocks/opportunities/opportunities.css
- blocks/pull-quote/pull-quote.css
- blocks/pull-quote/pull-quote.js
- blocks/stats/stats.css
- blocks/story-feed/story-feed.css
- blocks/story-feed/story-feed.js
- blocks/team-accordion/team-accordion.css
- styles/styles.css
- Closes #118
- Closes #117
- Closes #94
- Closes #121
- Closes #124
- Closes #103 
- Closes #161 
- https://fix-more-fonts-spacing--design-website--adobe.hlx3.page/
> chore: adjust fonts & spacing on stories, jobs detail

- blocks/people/people.js
- blocks/stories/stories.js
- blocks/story-feed/story-feed.js
- scripts/scripts.js
This adds JS to look at all links on a given page, and if they point to an external URL, we add a `target="_blank"` to them.
Lightly addresses #144 - but doesn't completely solve _that_ particular issue due to the nature of how we're using redirects & Helix. Instead, this look at any non-redirected external links and force them to open in a new tab/window.
Additionally, this wraps links around the images within story and people cards: #181 
- https://feat-add-external-links--design-website--adobe.hlx3.page/
> feat: all external links open in new tab/window

- blocks/people/people.css
Closes #183 
- https://fix-tag-sizes--design-website--adobe.hlx3.page/
> fix: make people tags the same size as story tags

- blocks/cards/cards.css
- blocks/stories/stories.css
- blocks/story-feed/story-feed.css
Closes #185
- https://fix-homepage-gap--design-website--adobe.hlx3.page/
> fix: add spacing below cards on homepage, stories, toolkit

- blocks/team-accordion/team-accordion.css
- blocks/team-accordion/team-accordion.js
- https://feat--accordion-updates--design-website--adobe.hlx3.page/team/
#108 
#109 
#85
> Adjustments to team accordion

- blocks/people/people.css
- blocks/stories/stories.css
- blocks/story-feed/story-feed.css
Closes #192
- https://fix-homepage-overflow--design-website--adobe.hlx3.page/
> fix: prevent images from overflowing

- styles/styles.css
Updates links within the Equal Opportunity Employer section on job postings to remove "default" link color.
- https://chore-about-ad-links--design-website--adobe.hlx3.page/
> chore: update job detail EOE link colors

- blocks/people/people.css
Closes #190
- https://chore-homepage-people-font-change--design-website--adobe.hlx3.page/
> chore: use intro type style for people titles

- blocks/product-clouds/product-clouds.css
- blocks/stats/stats.css
- blocks/team-accordion/team-accordion.css
> chore: aligin product, stats blocks with intro on Team page

- blocks/product-clouds/product-clouds.css
- blocks/stats/stats.css
- blocks/team-accordion/team-accordion.css
* Closes #206 
* Closes #207
* Closes #211
- https://chore-team-page-polish--design-website--adobe.hlx3.page/
> chore: adjust callout font-size on large screens

- blocks/people/people.css
- blocks/stories/stories.css
- blocks/story-feed/story-feed.css
* Closes #205
- https://chore-misc-polish--design-website--adobe.hlx3.page/
> chore: adjust tag size for stories, people cards

- blocks/cards/cards.css
- blocks/carousel/carousel.js
- blocks/jobs/jobs.css
- blocks/jobs/jobs.js
- blocks/lede/lede.css
- blocks/opportunities/opportunities.css
- blocks/opportunities/opportunities.js
- blocks/pull-quote/pull-quote.css
- blocks/stories/stories.js
- blocks/story-feed/story-feed.js
- blocks/team-accordion/team-accordion.css
- blocks/team-accordion/team-accordion.js
- styles/styles.css
* Adjusts Jobs landing "group" title font
* Adjusts Jobs landing "group" bottom spacing
* Adjusts Toolkit & Inclusive Design cards description font size
* Adjusts Toolkit & Inclusive Design cards description top margin
* Closes #201 
* Closes #204 
* Closes #219 
* Closes #223 
* Closes #224 
* Closes #225
* Closes #227 
* Closes #229 
* Closes #230 
* Closes #231   
* Closes #232
* Closes #234
- https://chore-misc-polish-2--design-website--adobe.hlx3.page/
> chore: misc. fit & finish

- scripts/colormap.js
Closes #235
- https://fix-toolkit-colors--design-website--adobe.hlx3.page/
> chore: add additional colors to colormap

- blocks/stats/stats.css
Closes #210
- https://chore-stats-heading-alingment--design-website--adobe.hlx3.page/
> chore: align stats heading with grid column

- blocks/lede/lede.js
Closes #236
- https://fix-hide-adobe-design-team--design-website--adobe.hlx3.page/
> fix: check against additional string when hiding author details

- blocks/carousel/carousel.css
- blocks/carousel/carousel.js
Addresses below issues.  Mainly around carousel layout and scroll indicator.
#251 
#252 
#253 
#244 
#245 
#246 
#247 
- https://feat--carousel-tweaks--design-website--adobe.hlx3.page/
> Feat  carousel tweaks

- blocks/team-accordion/team-accordion.css
- blocks/team-accordion/team-accordion.js
This adjusts behavior of accordion to only close when selected item is outside of viewport.
Addresses #228 #233 
- https://feat--accordion-tweaks--design-website--adobe.hlx3.page/team/
> Accordion behavior adjustments

- blocks/image-with-caption/image-with-caption.css
Closes #226
- https://chore-captioned-images-padding--design-website--adobe.hlx3.page/
> chore: reduce image padding for image-with-caption block

- blocks/lede/lede.css
- blocks/lede/lede.js
Refs #89 and #105 
* Re-positions the markup for the caption when on a profile page.
* Attempts to adjust spacing between image and caption by specifying a `1:1` ratio for the hero image - but this might look weird.
* Might need to refactor the hero area completely.
- https://chore-profile-image-cred--design-website--adobe.hlx3.page/
> wip: position hero caption directly below profile photo

- blocks/footer/footer.js
Closes #258
- https://chore-footer-logo-link--design-website--adobe.hlx3.page/
> feat: add link to footer logo

- blocks/carousel/carousel.js
- blocks/lede/lede.js
- blocks/people/people.js
- blocks/stories/stories.js
- blocks/story-feed/story-feed.js
Closes #256
- https://chore-remove-hash--design-website--adobe.hlx3.page/
> chore: remove '#' from tags site-wide

- blocks/cards/cards.css
- blocks/cards/cards.js
- blocks/collaborators/collaborators.css
Closes #264
Closes #265
- https://chore-inclusive-design-polish--design-website--adobe.hlx3.page/
> chore: adjust font sizes and spacing on Inclusive Design page

- blocks/carousel/carousel.css
- blocks/carousel/carousel.js
This fixes a number of issues related to the spacing and size of the carousel.
Closes #266
Closes #262
- https://fix-carousel-spacing--design-website--adobe.hlx3.page/
> fix: enforce aspect ratio for consistency across browsers

- blocks/cards/cards.js
Closes #272
- https://chore-link-inclusive-cards--design-website--adobe.hlx3.page/
> chore: add links to inclusive design cards

- blocks/cards/cards.css
- blocks/cards/cards.js
Links the card images on the Toolkit & Inclusive Design pages
- https://chore-link-card-imgs--design-website--adobe.hlx3.page/
> chore: link card images on toolkit

- blocks/cards/cards.css
- scripts/scripts.js
- tools/sidekick/config.js
- https://rofe-patch-2--design-website--adobe.hlx3.page/
> chore: enable sidekick in production

- blocks/team-accordion/team-accordion.css
Minor change to fix rendering issue in safari.
- https://bug-safari-glitch--design-website--adobe.hlx3.page/team/
> add will-change to fix safari glitch

- blocks/story-feed/story-feed.js
https://sorted-stories--design-website--adobe.hlx.page/stories/
vs. 
https://main--design-website--adobe.hlx.page/stories/
> chore: add story sorting

- 404.html
@pfulton thanks for adding the header and footer to this, hopefully it wasn't too difficult.
I made some changes so that the canvas isn't fixed and instead sits inside the content.  Since the footer extends below the fold this accounts for scrolling etc.  I also made an adjustment to the background sizing so that it doesn't get overridden by the other stylesheet coming in.
> 404 adjustments

- blocks/story-feed/story-feed.js
- head.html
https://twitter-meta--design-website--adobe.hlx.page/stories/process/how-accessibility-bluelines-shaped-fresco
vs. 
https://main--design-website--adobe.hlx.page/stories/process/how-accessibility-bluelines-shaped-fresco
> feat: twitter meta

- blocks/carousel/carousel.css
- blocks/carousel/carousel.js
- blocks/lede/lede.css
- blocks/lede/lede.js
- blocks/stories/stories.css
- blocks/stories/stories.js
- blocks/story-feed/story-feed.css
- blocks/story-feed/story-feed.js
- scripts/tag-link.js
This creates a feature where tags for articles are displayed as links back to a listing page containing similarly tagged articles. The feature request is detailed on the project [Trello board](https://trello.com/c/PxmK5WJ2/6-live-story-tag-links).
- https://sbx-story-tag--design-website--adobe.hlx.page/
- https://sbx-story-tag--design-website--adobe.hlx.page/stories/our-people/
- https://sbx-story-tag--design-website--adobe.hlx.page/stories/our-people/profile/
- https://sbx-story-tag--design-website--adobe.hlx.page/stories/community/
- https://sbx-story-tag--design-website--adobe.hlx.page/stories/design-for-scale/
- https://sbx-story-tag--design-website--adobe.hlx.page/stories/leading-design/
- https://sbx-story-tag--design-website--adobe.hlx.page/stories/process/
Changes …
> feat: Add links to tags, update tag url checks

- scripts/scripts.js
- styles/styles.css
This PR removes an unneeded container and addresses changes to the layout to account for that.
Relocation of EOE copy.
Tested on a demo page to preview the changes: https://sbx-remove-eoe--design-website--adobe.hlx.page/jobs/job-posts/content-strategy/r127720-content-designer
> feat: Remove EOE container

- styles/styles.css
This PR fixes an issue with the hamburger menu not opening or closing the menu on mobile view
[ADB-67](https://sparkbox.atlassian.net/browse/ADB-67)
Tested on preview site: https://sbx-fix-hamburger-menu--design-website--adobe.hlx.page/stories/
> fix: Hamburger menu on mobile view

- scripts/get-author-titles.js
- scripts/scripts.js
https://sbx-fix-home--design-website--adobe.hlx.page/
> fix: json file setup

- scripts/format-card-byline.js
- scripts/get-author-titles.js
This PR fixes a bug that didn't allow for authors with job titles including an HTML entity to fully display.
[ADB-70](https://sparkbox.atlassian.net/browse/ADB-70)
Tested on preview page: https://sbx-fix-title-with-ampersand--design-website--adobe.hlx.page/
> fix: byline with HTML entities

- scripts/scripts.js
see https://fix-cwv--design-website--adobe.hlx.live/?rum=on
> fix(rum): add cwv measurement in delayed

- scripts/scripts.js
- styles/styles.css
https://a11y-tweaks--design-website--adobe.aem.live/
vs.
https://main--design-website--adobe.aem.live/
> chore: add a11y tweaks

- styles/styles.css
https://about-adobe-reduced-font-size--design-website--adobe.aem.page/jobs/job-posts/content-strategy/r146739-sr-content-strategist
vs.
https://main--design-website--adobe.aem.page/jobs/job-posts/content-strategy/r146739-sr-content-strategist
> chore: reduce font-size for about adobe footer on desktop

- scripts/scripts.js
Migrate to RUM v2
Before: https://main--design-website--adobe.hlx.live/?rum=on
After: https://rum-v2--design-website--adobe.hlx.live/?rum=on
> feat: RUM v2
