adobe/design-website

helix-query.yaml

Makes it more readable, and it avoids making copy+paste errors when creating a new version of the same site.

fix: use relative target for index

---

blocks/lede/lede.css

Fixes an issue where we were using a static color for story title, subtitle and tag.
- https://fix--article-heading-colors--design-website--adobe.hlx3.page/

fix: use correct vars for story titles and tag

---

styles/styles.css

Adds `position: sticky` at mobile+ sizes to Job details meta container.
Closes #70 
- https://feat--sticky-job-meta--design-website--adobe.hlx3.page/

feat: sticky positioning on job detail meta info

---

blocks/lede/lede.css
blocks/lede/lede.js

Adds a new "enhanced author details" block to each story where the author isn't "Adobe Design".
Refs #56 
- https://feat-enhanced-author-block--design-website--adobe.hlx3.page/

feat: enhanced author details block

---

styles/styles.css

iOS devices were showing the `.blended-background` linear gradient on the jobs detail pages. This forces that element to be `display: none` on those pages.
Closes #83
- https://fix-jobs-background--design-website--adobe.hlx3.page/

fix: remove errant gradient bg on jobs detail page

---

blocks/cards/cards.css
blocks/cards/cards.js
blocks/lede/lede.css
blocks/lede/lede.js
blocks/opportunities/opportunities.css
blocks/opportunities/opportunities.js
blocks/story-feed/story-feed.css
blocks/story-feed/story-feed.js
blocks/team-accordion/team-accordion.css
blocks/team-accordion/team-accordion.js
scripts/scripts.js
styles/styles.css

Major refactor of all page titles (`h1`).
* creates common `.page-title` selector styles
* creates custom props to support `.page-title`
* adds new selector to `h1` elements, site-wide
Closes #114, Closes #93 
- https://refactor-page-title--design-website--adobe.hlx3.page/

refactor: page title

---

blocks/cards/cards.css
blocks/collaborators/collaborators.css

This writes CSS to prevent image overflows on both the Toolkit landing page and on the Inclusive Design page. It also specifies an aspect ratio for profile photos.
Closes #131
- https://fix-toolkit-inclusive-design--design-website--adobe.hlx3.page/

fix: images overflowing on toolkit and inclusive design pages

---

blocks/jobs/jobs.js
blocks/opportunities/opportunities.css

On the `/jobs/` landing page, this forces "experience design" positions to be listed in the first column, and the remaining positions to be listed in the second column. Closes #171 
Additionally, this removes the "position type" designation on job listings on the homepage.
- https://chore-opportunities-columns--design-website--adobe.hlx3.page/

chore: specific order on jobs landing, remove homepage job position types

---

styles/lazy-styles.css
styles/styles.css

This swaps the bg image for a css gradient bg.  I did remove the 100% on the html and body tag, which prevented the gradient from filling the content.  It didn't seem to cause any issues but  let me know if there is a reason to keep those in.
- https://feat--gradient--design-website--adobe.hlx3.page/

add gradient bg

---

scripts/scripts.js

currently it is relatively hard to handle pages that have a redirect on them for authors, as the pages get redirected as soon as they are (pre)viewed, which makes it hard to `publish`. this new way of redirect handling automatically suppresses the redirect on `.page` and `.live` URLs and only actually redirects on the production URL...
https://better-redirect--design-website--adobe.hlx3.page/toolkit/inclusive-design-card
...to test the redirect behavior in production...
https://better-redirect--design-website--adobe.hlx3.page/toolkit/inclusive-design-card?redirect=on 
can be used.

chore: better redirect handling for authoring

---

blocks/lede/lede.js

This uses the data from the plain author query to populate the author's name, rather than using the meta tag, which was stripping out special characters from author names.
Closes #115
- https://fix-author-name-in-details--design-website--adobe.hlx3.page/

fix: use different data source for author name in author details block

---

blocks/team-accordion/team-accordion.css

This removes a superfluous `grid` from the accordion container, and fixes an issue where text was overflowing and being cut off in Safari.
Closes #257
Closes #248 
- https://fix--accordion-overflow--design-website--adobe.hlx3.page/

fix: prevent accordion overflow

---

scripts/scripts.js

going to a url like:
https://adobe.design/jobs/job-posts/experience-design/r122213-sr-experience-designer
with missing content does not show the correct 404 page.
- https://404-issue--design-website--adobe.hlx.page/404.html

404 pages don't always show up for missing content

---

helix-sitemap.yaml

This PR adds a file `helix-sitemap.yaml`.
No sitemap generated for https://adobe.design.
Demo preview: https://sbx-add-sitemap--design-website--adobe.hlx.page/

chore: Add sitemap

---

blocks/embed/embed.css
blocks/embed/embed.js

Similarly to #301, this PR creates a block for displaying embeds from social media, such as Instagram and Twitter. The block is called `embed` and expects the first and only table cell to contain the link to a social media post.
This will allow content creators to link add social media posts to stories.
Tested on a demo page to preview the feature: https://sbx-social-media-embeds--design-website--adobe.hlx.page/drafts/dev/embed-draft

feat: Add embed block for social media embeds

---

scripts/scripts.js

URLs For testing:
- [Demo of Stories Article internal links that open in a new tab or window](https://sbx-internal-links-new-tab--design-website--adobe.hlx.page/stories/process/a-modern-adobe-acrobat)
- [Demo of Not-Stories page with internal links that open in the same tab](https://sbx-internal-links-new-tab--design-website--adobe.hlx.page/toolkit/inclusive-design/)
This work expands on the function which sets queries all links on a page and sets external links to open in a new tab, so that specific content areas links will open in a new tab for internal links as well.
The original issue can be found on [Trello](https://trello.com/c/ul2Otvgy/10-open-internal-links-within-articles-in-a-new-tab)
Currently all external links site-wide open in a new tab/window. However to keep readers of …

feat: open links in articles in new tab

---

scripts/scripts.js

the introduction of the sitemap sheet created a side effect that changed the structure of the `lookupPages()` function slightly, which revealed an "undefined" in the carousel...
https://fix-lookup-pages--design-website--adobe.hlx.page/
vs.
https://main--design-website--adobe.hlx.page/

fix: lookupPages sideeffect

---

blocks/multi-image/multi-image.css
blocks/multi-image/multi-image.js

This PR creates a block for displaying two or three images side-by-side. The block is called `multi-image` and expects a single row with either two or three cells. Each cell includes an image and a caption. If less than two or more than three images are added, then the images stack on all screen sizes.
This will allow content creators to display up to three images in a row in stories as needed.
Tested on a demo page to preview the feature: https://sbx-side-by-side-images--design-website--adobe.hlx.page/drafts/dev/images-draft

feat: Add images block for side-by-side image embeds

---

blocks/story-feed/story-feed.js

This PR fixes a bug where `/stories/` also listed cards for story tags.
[ADB-54](https://sparkbox.atlassian.net/browse/ADB-54)
`story-feed` block should only generate cards for Stories.
Before fix (note 'Process' and 'Our People' at bottom of feed): https://main--design-website--adobe.hlx.page/stories/
After fix: https://sbx-fix-stories-listing-subsection-pages--design-website--adobe.hlx.page/stories/

fix: Story feed block listing subsection pages

---

blocks/cta/cta.css
blocks/cta/cta.js

This PR creates new block which will replace the current Join Us section the homepage, which includes the `jobs` and `stats` block. The block is called `cta` and accepts an optional field of links to job postings.
[ADB-48](https://sparkbox.atlassian.net/browse/ADB-48)
The need to have a unified CTA that can be used throughout pages on the website. Used on the homepage, the CTA will span the width of the window. Used on a Stories page, the CTA will span the width of content.
CTA on homepage: https://sbx-jobs-block-adjustment--design-website--adobe.hlx.page/drafts/dev/cta-homepage-draft
CTA on Stories page: https://sbx-jobs-block-adjustment--design-website--adobe.hlx.page/drafts/dev/cta-stories-draft
Homepage:
Stories page:

feat: Add cta block

---

blocks/opportunities/opportunities.js
scripts/scripts.js
styles/styles.css

This PR fixes the issue of the 404 message on the jobs page inconsistently rendering on Safari.
[ADB-59](https://sparkbox.atlassian.net/browse/ADB-59)
Tested in the preview page in Safari 15: https://sbx-fix-jobs-404-safari--design-website--adobe.hlx.page/jobs/?job=404

fix: Jobs 404 message not rendering on Safari

---

blocks/embed/embed.js

This PR adds the ability for the `embed` block to handle embedding the Simplecast player.
[ADB-65](https://sparkbox.atlassian.net/browse/ADB-65)
Need functionality for a future Story.
Tested in preview site: https://sbx--simplecast-embed--design-website--adobe.hlx.page/drafts/dev/embed-draft

feat: Add Simplecast handling to embed block

---

blocks/image-with-text/image-with-text.css
blocks/image-with-text/image-with-text.js

This PR creates a new block called `image with text`, which displays a two-column layout with image on one side and text on the other. Image and text content can be displayed in either order.
[ADB-46](https://sparkbox.atlassian.net/browse/ADB-46)
The main use-case for this block will be for an upcoming page.
Tested on preview site: https://sbx-image-with-text--design-website--adobe.hlx.page/drafts/dev/profiles-draft

feat: Create Image With Text block

---

blocks/lede/lede.css
blocks/lede/lede.js

This PR adds the ability to display more than one author in a story's byline and article.
[ADB-44](https://sparkbox.atlassian.net/browse/ADB-44) and [ADB-55](https://sparkbox.atlassian.net/browse/ADB-55)
Handle an upcoming story with two authors.
Tested on the preview page: https://sbx-multi-authors-article--design-website--adobe.hlx.page/drafts/dev/multiauthor-draft
Multiple authors in byline:
Multiple authors in footer:

feat: Mutliple authors in articles

---

blocks/stories/stories.css
blocks/stories/stories.js
blocks/story-feed/story-feed.css
blocks/story-feed/story-feed.js
scripts/format-card-byline.js
scripts/get-author-titles.js
scripts/scripts.js

This PR adds the ability to display more than one author on a story card.
[ADB-56](https://sparkbox.atlassian.net/browse/ADB-56)
Handle an upcoming story with two authors.
Hard-coded test data into `story.js` and `story-feed.js` to generate view seen in screenshots below.
Original functionality of homepage not affected, save for removal of 'by' next to author's name: https://sbx-multi-authors-cards--design-website--adobe.hlx.page/
Ditto Stories page: https://sbx-multi-authors-cards--design-website--adobe.hlx.page/stories/

feat: Multiple authors on story cards

---

blocks/opportunities/opportunities.js

This PR affects the `/jobs/` route, and will prevent headings for departments without any job listings from appearing on the page.
[ADB-68](https://sparkbox.atlassian.net/browse/ADB-68)
Tested on preview URL: https://sbx-hide-empty-departments--design-website--adobe.hlx.page/jobs/

feat: hide departments without job listings

---

blocks/collaborators/collaborators.css

This PR affects the `collaborators` block, and adds a margin when it is used on the site other than the Inclusive Design page.
[ADB-69](https://sparkbox.atlassian.net/browse/ADB-69)
Preview Inclusive Design page: https://sbx-collaborators-styling--design-website--adobe.hlx.page/toolkit/inclusive-design/
Preview Product Equity page: https://sbx-collaborators-styling--design-website--adobe.hlx.page/toolkit/product-equity-at-adobe

fix: add margin to `collaborators`

---

scripts/scripts.js

https://update-lookup-pages-function--design-website--adobe.hlx.page/drafts/product-equity-at-adobe
This reverts the `lookupPages` function to only use the `query-index.json` file and not the `query-dev.json` file which was set up to test on branches.

fix: Revert JSON file to only use index version

---

scripts/scripts.js

https://main--design-website--adobe.hlx.live/
vs.
https://rum-hlx-page--design-website--adobe.hlx.live/

chore: move hlx3 to hlx

---

blocks/lede/lede.js
scripts/get-author-titles.js

https://authorbox-on--design-website--adobe.aem.page/stories/community/adobe-design-talks-why-generative-ai-needs-design-leadership
vs. 
https://main--design-website--adobe.aem.page/stories/community/adobe-design-talks-why-generative-ai-needs-design-leadership

chore: remove special case to suppress authorbox
